extends Node

const PLAYER_ACCELERATION_VALUE = 1000
const PLAYER_ROTATION_VALUE = 0.15
const PLAYER_SPEED_THRESHOLD_FAST = PLAYER_ACCELERATION_VALUE * 0.75
const PLAYER_SPEED_THRESHOLD_SLOW = PLAYER_ACCELERATION_VALUE * 0.3
const PLAYER_FRICTION_VALUE = PLAYER_ACCELERATION_VALUE / 10.0
const PLAYER_MAX_VELOCITY = PLAYER_ACCELERATION_VALUE
